<?php
define('PATH_ROOT', realpath(__DIR__ . DIRECTORY_SEPARATOR . '..'));
const PATH_LOGS = PATH_ROOT . DIRECTORY_SEPARATOR . 'Logs';
const PATH_TESTS = PATH_ROOT . DIRECTORY_SEPARATOR . 'Tests';
const PATH_COMPOSER_AUTOLOADER = PATH_ROOT . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';
const PATH_MODULES = PATH_ROOT . DIRECTORY_SEPARATOR . 'App' . DIRECTORY_SEPARATOR . 'Modules';
define('PATH_TEMP', sys_get_temp_dir());