name: dominus-api
services:
  api:
    build:
      dockerfile: api.Dockerfile
    env_file:
      - .env
    volumes:
      - "../src:/api"
      - "../tmp:/tmp"
    ports:
      - "8080:80"
    restart: unless-stopped
