<?php
const PATH_DEBUG_HELPERS = PATH_ROOT . DIRECTORY_SEPARATOR . 'Dominus' . DIRECTORY_SEPARATOR . 'System' . DIRECTORY_SEPARATOR . 'DebugHelpers';

require PATH_DEBUG_HELPERS . DIRECTORY_SEPARATOR . 'Functions.php';